apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mysql-rs
  labels:
    app: mysql-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql-rs-pod
  template:
    metadata:
      labels:
        app: mysql-rs-pod
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
          # Test, use secret in prod
        - name: MYSQL_ROOT_PASSWORD
          value: MyV3ryS3curePa55
